on: [push, pull_request]

jobs:
  publish:
    name: build and publish to pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set version from tag
        if: startsWith(github.ref, 'refs/tags')
        run: |
          # from refs/tags/1.2.3 get 1.2.3
          VERSION=$(echo $GITHUB_REF | sed 's#.*/##')
          PLACEHOLDER='version="develop"'
          VERSION_FILE='setup.py'
          grep "$PLACEHOLDER" "$VERSION_FILE"
          sed -i "s/$PLACEHOLDER/version=\"${VERSION}\"/" "$VERSION_FILE"
        shell: bash

      - name: install dependencies & build
        run: |
          pip3 install setuptools wheel
          python3 setup.py sdist bdist_wheel

      - name: publish to Test PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: publish to PyPi
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}